const mongoose = require('mongoose');

const itemSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  type: String,
  sqm: Number,
  surface: Number,
  price: Number,
  imagePath: String,
  city: String,
  cityArea: String,
  areaCode: String,
  street: String,
  zipCode: String,
  floor: String,
  furnished: String,
  rooms: Number,
  bedrooms: Number,
  beds: Number,
  bathrooms: Number,
  heating: String,
  balcony: Number,
  duplex: Number,
  loftApartment: Number,
  penthouse: Number,
  lastFloor: Number,
  description: String,
  deposit: Boolean,
  availableFrom: Date,
  cooling: Boolean,
  internet: Boolean,
  cableTv: Boolean,
  phone: Boolean,
  washingMachine: Boolean,
  dishWasher: Boolean,
  floorHeating: Boolean,
  pantry: Boolean,
  lift: Boolean,
  basement: Boolean,
  intercom: Boolean,
  videoSurv: Boolean,
  garage: Boolean,
  parkingPlace: Boolean,
  garden: Boolean,
  pool: Boolean,
  creator: String,
  date: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Item', itemSchema);
